OLED_ENABLE = no
ENCODER_ENABLE = yes      # Enables the use of one or more encoders
RGBLIGHT_ENABLE = no      # Enable keyboard RGB underglow
UNICODEMAP_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = no
COMBO_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no

SRC += unicode.c
SRC += casemodes.c
SRC += custom_autoshift.c
SRC += combos.c
SRC += user_keycodes.c
